### ISSUE TITLE
`AttributeError: 'NoneType' object has no attribute 'children'` when run `python src/get_current_day.py`

### ISSUE THREAD

**Issue by sundevilyang** [kevinjalbert/notion-toolbox#12]
@kevinjalbert hey kevin, I got the following error when run `python3 src/get_current_day.py`

```
python src/get_current_day.py
Traceback (most recent call last):
  File "src/get_current_day.py", line 10, in <module>
    print(notion_api.current_week().children)
  File "/Users/ywen8/.pyenv/versions/3.8.1/lib/python3.8/site-packages/cachetools/__init__.py", line 46, in wrapper
    v = func(*args, **kwargs)
  File "/Users/ywen8/.pyenv/versions/3.8.1/lib/python3.8/site-packages/notionscripts/notion_api.py", line 48, in current_week
    if week_page.title.startswith("Week " + week_number):
AttributeError: 'Block' object has no attribute 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/get_current_day.py", line 16, in <module>
    sys.stderr.write(e)
TypeError: write() argument must be str, not AttributeError
```

**Comment by sundevilyang** [comment]
I review the 48 line of notion_api.py file, 

```
    def current_week(self):
        found_week = None
        current_date = datetime.now()

        # Sunday Starts the week
        week_number = str(current_date.isocalendar()[
                         1] + (current_date.isoweekday() == 7))

        for week_page in self.current_year().children:
            if week_page.title.startswith("Week " + week_number):
                found_week = week_page
                break
            else:
                next

        return found_week
```
it goes to the year page for looking the current week page, my year page as the following pic indicates: 
![image](https://user-images.githubusercontent.com/1499214/74620528-74737000-5174-11ea-8859-77b7d204478e.png)

What may cause this error ?

**Comment by kevinjalbert** [comment]
@sundevilyang I'm curious what was the issue in this case?

I seems like maybe you had an extra block hanging around in this page? Thus the `AttributeError: 'Block' object has no attribute 'title'`?
