### ISSUE TITLE
Issue with get tasks

### ISSUE THREAD

**Issue by hanj0415** [kevinjalbert/notion-toolbox#22]
It seems it is related to #20, I executed get_tasks.py, and got below.
```
❯ python3 get_tasks.py
Traceback (most recent call last):
  File "get_tasks.py", line 20, in <module>
    } for row in notion_api.tasks_database().default_query().execute()]
  File "/Volumes/Home/rickhan/Library/Python/3.7/lib/python/site-packages/notion/collection.py", line 223, in default_query
    return self.build_query(**self.get("query2", {}))
  File "/Volumes/Home/rickhan/Library/Python/3.7/lib/python/site-packages/notion/collection.py", line 219, in build_query
    collection=self.collection, collection_view=self, **kwargs
  File "/Volumes/Home/rickhan/Library/Python/3.7/lib/python/site-packages/notion/collection.py", line 301, in __init__
    assert not (aggregate and aggregations), "Use only one of `aggregate` or `aggregations` (old vs new format)"
AssertionError: Use only one of `aggregate` or `aggregations` (old vs new format)
```
This might be the reason why I have "Nothing" when I query the current task as well.

**Comment by hanj0415** [comment]
I'm still having trouble getting the tasks. Please refer to
> "Use only one of `aggregate` or `aggregations` (old vs new format)"
AssertionError: Use only one of `aggregate` or `aggregations` (old vs new format)

**Comment by kevinjalbert** [comment]
@hanj0415 are you on the recent commit? I don't have this issue on my version (which is the lastest for notion-toolbox as of today). I am able to use `get_current_tasks.py` and `get_tasks.py` successfully.
