### ISSUE TITLE
Trying to deploy heroku app fails

### ISSUE THREAD

**Issue by naveenjohnsonv** [kevinjalbert/notion-toolbox#23]
Getting error on deploying heroku app. Here's the log:

```
-----> Python app detected

 !     Python has released a security update! Please consider upgrading to python-3.7.9

       Learn More: https://devcenter.heroku.com/articles/python-runtimes

-----> Installing python-3.7.6

-----> Installing pip 20.1.1, setuptools 47.1.1 and wheel 0.34.2

-----> Installing SQLite3

-----> Installing requirements with pip

       Collecting git+https://github.com/kevinjalbert/notion-py.git (from -r /tmp/build_18d77bd7_/./server/requirements.txt (line 2))

         Cloning https://github.com/kevinjalbert/notion-py.git to /tmp/pip-req-build-vgx1cmtm

         Running command git clone -q https://github.com/kevinjalbert/notion-py.git /tmp/pip-req-build-vgx1cmtm

           ERROR: Command errored out with exit status 1:

            command: /app/.heroku/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-vgx1cmtm/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-vgx1cmtm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-18vvwrjj

                cwd: /tmp/pip-req-build-vgx1cmtm/

           Complete output (7 lines):

           Traceback (most recent call last):

             File "<string>", line 1, in <module>

             File "/tmp/pip-req-build-vgx1cmtm/setup.py", line 12, in <module>

               install_requires = [str(ir.req) for ir in reqs]

             File "/tmp/pip-req-build-vgx1cmtm/setup.py", line 12, in <listcomp>

               install_requires = [str(ir.req) for ir in reqs]

           AttributeError: 'ParsedRequirement' object has no attribute 'req'

           ----------------------------------------

       ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

 !     Push rejected, failed to compile Python app.

 !     Push failed
```

**Comment by naveenjohnsonv** [comment]
So I created manually through heroku-cli and it works so I guess there's a problem with the deploy button

**Comment by naveenjohnsonv** [comment]
But somehow despite adding all the env variables the command still doesn't add the task
Applet fails in IFTTT. Here's the heroku log when I try the voice command:

```
2020-09-11T04:54:32.184753+00:00 app[web.1]: -> Initial Transition Detected

2020-09-11T04:55:11.749577+00:00 heroku[router]: at=info method=GET path="/add_task?title=testing" host=guarded-inlet-22010.herokuapp.com request_id=7a39fad7-e3fa-4b9a-bb1e-02293f5fba5a fwd="34.224.60.102" dyno=web.1 connect=1ms service=2ms status=405 bytes=377 protocol=https

2020-09-11T04:55:11.751591+00:00 app[web.1]: 10.35.254.83 - - [11/Sep/2020:10:25:11 +0530] "GET /add_task?title=testing HTTP/1.1" 405 178 "-" "-"

2020-09-11T04:55:25.893304+00:00 app[web.1]: Processing 'Submit expense report'

2020-09-11T04:55:27.117714+00:00 app[web.1]: Processing 'Publish Blog Post'

2020-09-11T04:55:28.593445+00:00 app[web.1]: Processing 'Improve git aliases'

2020-09-11T04:55:29.722482+00:00 app[web.1]: Processing 'Hey why'

2020-09-11T04:56:25.193787+00:00 app[web.1]: Processing 'Submit expense report'

2020-09-11T04:56:26.578016+00:00 app[web.1]: Processing 'Publish Blog Post'

2020-09-11T04:56:28.111756+00:00 app[web.1]: Processing 'Improve git aliases'

2020-09-11T04:56:29.412265+00:00 app[web.1]: Processing 'Hey why'

2020-09-11T04:57:25.503161+00:00 app[web.1]: Processing 'Submit expense report'

2020-09-11T04:57:26.933214+00:00 app[web.1]: Processing 'Publish Blog Post'

2020-09-11T04:57:28.034156+00:00 app[web.1]: Processing 'Improve git aliases'

2020-09-11T04:57:29.192457+00:00 app[web.1]: Processing 'Hey why'

2020-09-11T04:58:25.211394+00:00 app[web.1]: Processing 'Submit expense report'

2020-09-11T04:58:26.724633+00:00 app[web.1]: Processing 'Publish Blog Post'

2020-09-11T04:58:28.383531+00:00 app[web.1]: Processing 'Improve git aliases'

2020-09-11T04:58:33.558348+00:00 app[web.1]: Processing 'Hey why'



```

**Comment by kevinjalbert** [comment]
🤔 Hmm to be honest I'm not 100% sure what the issue could be here. Quick searching makes it seem like some pip version issue.

I'm curious if you tried other things to get this working?

**Comment by naveenjohnsonv** [comment]
Yeah I figured someone must've tried to fix it and found one of your project's forks had it working. Just two new commits https://github.com/bkraeling/notion-toolbox/commit/f77fc528b22f93e6996b28d516d3e5bf6730c398 and https://github.com/bkraeling/notion-toolbox/commit/f77fc528b22f93e6996b28d516d3e5bf6730c398 . Maybe look into those, seems to me to be an in issue in notion-py

**Comment by naveenjohnsonv** [comment]
I appreciate your work though, it's been really helpful. I know the server project is still in the works but I'm curious, is add_notes still working through assistant for you? add_task works just fine but add_note doesn't seem to be making any changes to the current days' notes. I'm not sure if it's a problem in your code or happened due to the changes in your project's fork that I'm currently using to make heroku deploy. If you can, kindly look into that too. The add_task returns 500 and ifttt flags an error even though the tasks actually get added, add_notes returns 500 but the notes don't get added.

**Comment by kevinjalbert** [comment]
@naveenjohnsonv I'm sorry for the delay. I haven't actually been using this project much recently (although will likely get back to it eventually).

If you figure how to fix the issue, I'd appreciate a PR on this project 😄.

As for your issue with the errors, it might be best to put some logging in the server and see what the response exception is and go from there.

**Comment by DavidDoesDev** [comment]
Stupid question—where do I put the secrets.NOTION_TOKEN and secrets.NOTION_TEST_PARENT_PAGE_ID (see [heroku error](https://www.dropbox.com/s/w3ldq7axxxdq49t/herokufail.png?dl=0))? Not directly in the ci.yml file, right?

**Comment by kevinjalbert** [comment]
@DavidDoesDev This is part of the new revamp, and those secrets.XXXX values are for the CI testing in GitHub. From what I gather they shouldn't factor in the heroku deployment. If you forked the repo and wanted CI to run on your own fork, then you'd have to set those secret values for the GitHub Action.
