### ISSUE TITLE
notion_api.py cannot find what it needs to import

### ISSUE THREAD

**Issue by erauner12** [kevinjalbert/notion-toolbox#24]
`/src  python3 add_task.py
Traceback (most recent call last):
  File "add_task.py", line 7, in <module>
    from notion_api import notion_api
  File "/Users/er046256/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.E09BB44C-123F-4ED3-9D1F-6CCE03F76523/src/notion_api.py", line 1, in <module>
    from notionscripts.notion_api import NotionApi
ModuleNotFoundError: No module named 'notionscripts'`

I followed the instructions on the readme and tried to use the workflow. I noticed it was not working even though I had my cookie and paths in the config file. I tried to just run one of the python scripts and it cannot find the scripts in the shared directory? I do not recall copying those over. I'm not sure where to copy them since we are also supposed to have copied over the contents of the alfred directory.

**Comment by erauner12** [comment]
I just tried to move the setup.py and notionscripts directory into the <workflow dir>/src
`/src  python3 add_task.py
Traceback (most recent call last):
  File "add_task.py", line 7, in <module>
    from notion_api import notion_api
  File "/Users/er046256/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.E09BB44C-123F-4ED3-9D1F-6CCE03F76523/src/notion_api.py", line 1, in <module>
    from notionscripts.notion_api import NotionApi
  File "/Users/er046256/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.E09BB44C-123F-4ED3-9D1F-6CCE03F76523/src/notionscripts/notion_api.py", line 6, in <module>
    from notion.client import NotionClient
ModuleNotFoundError: No module named 'notion'`

Now it cannot find the module called notion

**Comment by erauner12** [comment]
got it working. the requirements file did not install notion-so.py properly. I also had to manually copy over the notionscripts directory in to make it work
